version: '3.9'

services:
  db:
    container_name: postgres_django
    image: postgres:15-alpine
    environment:
      - pg_data:/var/lib/postgresql/data
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  backend_admin:
    build: .

    volumes:
      - ./:/app
    ports:
      - 8000:8000
    depends_on:
      - db
    entrypoint: [ 'sh', 'entrypoint.sh' ]

  redis:
    restart: always
    image: "redis:alpine"
    container_name: "redis"
    ports:
      - "6379:6380"

  celery:
    restart: always
    env_file:
      - .env
    build:
      context: .
    command: bash -c "cd online && celery -A online worker -l info"
    depends_on:
      - redis
  celery-beat:
    restart: always
    build:
      context: .
    command: bash -c "cd online && celery -A online  beat -l info"
    depends_on:
      - redis
      - celery

volumes:
  pgdata: null