# Generated by Django 4.2 on 2023-04-04 13:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=25, verbose_name="Profile first_name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=25, verbose_name="Profile last_name"),
                ),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="profile",
                        verbose_name="Profile Image",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        max_length=20, verbose_name="Profile phone_number"
                    ),
                ),
            ],
        ),
    ]
