# Generated by Django 4.2 on 2023-04-09 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_remove_appointment_service_appointment_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('appointment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='booking.appointment')),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            bases=('booking.appointment',),
        ),
    ]
