# Generated by Django 4.2 on 2023-04-10 12:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_profile_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0002_remove_appointment_service_appointment_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(default=datetime.datetime.now)),
                ('time', models.CharField(choices=[('10.00 PM', '10.00 PM'), ('10:30 PM', '10:30 PM'), ('11.00 PM', '11.00 PM'), ('11:30 PM', '11:30 PM'), ('12.00 PM', '12.00 PM'), ('12:30 PM', '12:30 PM'), ('13.00 PM', '13.00 PM'), ('13:30 PM', '13:30 PM'), ('14.00 PM', '14.00 PM'), ('14:30 PM', '14:30 PM'), ('15.00 PM', '15.00 PM'), ('15:30 PM', '15:30 PM'), ('16.00 PM', '16.00 PM'), ('16:30 PM', '16:30 PM'), ('17.00 PM', '17.00 PM'), ('17:30 PM', '17:30 PM'), ('18.00 PM', '18.00 PM')], default='3 PM', max_length=10)),
                ('time_ordered', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.service')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
