# Generated by Django 4.2 on 2023-05-04 12:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0004_bookingsettings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="time",
            field=models.CharField(
                choices=[
                    ("10.00 PM", "10.00 PM"),
                    ("10:30 PM", "10:30 PM"),
                    ("11.00 PM", "11.00 PM"),
                    ("11:30 PM", "11:30 PM"),
                    ("12.00 PM", "12.00 PM"),
                    ("12:30 PM", "12:30 PM"),
                    ("13.00 PM", "13.00 PM"),
                    ("13:30 PM", "13:30 PM"),
                    ("14.00 PM", "14.00 PM"),
                    ("14:30 PM", "14:30 PM"),
                    ("15.00 PM", "15.00 PM"),
                    ("15:30 PM", "15:30 PM"),
                    ("16.00 PM", "16.00 PM"),
                    ("16:30 PM", "16:30 PM"),
                    ("17.00 PM", "17.00 PM"),
                    ("17:30 PM", "17:30 PM"),
                    ("18.00 PM", "18.00 PM"),
                ],
                default="3 PM",
                max_length=40,
            ),
        ),
    ]
